### PR TITLE
Adding Chinese localization

### PR DESCRIPTION
**Pull request by jdonee**

### CODE REVIEW

**Comment by hengaini2055** [comment]
The project is so amazing, but the stars is so fewer. Why?

**Comment by jdonee** [comment]
> The project is so amazing, but the stars is so fewer. Why?

I don't know too

**Comment by iansadovy** [comment]
Thanks!

**Comment by webdatarocksteam** [comment]
Hi @jdonee and @hengaini2055, 
Thank you for supporting our product!
We're happy that you like it. And we'd be even happier if you shared information about WebDataRocks with your friends or colleagues and gave your feedback on Capterra: 

https://www.capterra.com/p/170630/WebDataRocks-Free-Web-Reporting-Tool/

Your feedback is what helps us enhance WebDataRocks every day.

Best regards,

WebDataRocks Team

**Pull request merged**
